use hotelbookingsystem;

-- 1. Display the hotel name, branch name, city, address, and manager name for all active branches.

select h.hotel_name, b.branch_name, b.city, b.address, b.manager_name, b.branch_status
from hotel h
join branch b
on h.hotel_id = b.hotel_id
where b.branch_status = 'active'
order by h.hotel_name;

-- 2. Display the customer name, reservation date, room number, reservation status, and total amount for confirmed reservations.

select c.customer_name, r.reservation_date, rm.room_number, r.reservation_status, r.total_amount
from reservation r
join customer c
on r.customer_id = c.customer_id
join room rm
on r.room_id = rm.room_id
where r.reservation_status = 'confirmed'
order by r.reservation_date desc;

-- 3. Display the employee name, department name, branch name, and salary of employees whose salary is greater than ₹30,000.

select e.employee_name, d.department_name, b.branch_name, e.salary
from employee e
join department d
on e.department_id = d.department_id
join branch b
on e.branch_id = b.branch_id
where e.salary > 30000
order by e.salary desc;

-- 4. Display the available rooms with branch name, room type, bed type, and price per night.

select b.branch_name, rt.room_type_name, rt.bed_type, rt.price_per_night, r.room_status
from room r
join branch b
on r.branch_id = b.branch_id
join room_type rt
on r.room_type_id = rt.room_type_id
where r.room_status = 'available'
order by rt.price_per_night desc;

-- 5. Display the customer name, rating, comments, and feedback date for customers who have given a rating of 4 or above.

select c.customer_name, f.rating, f.comments, f.feedback_date
from feedback f
join customer c
on f.customer_id = c.customer_id
where f.rating >= 4
order by f.rating desc;

-- 6. Display the total revenue generated by each hotel and arrange the result in descending order of revenue.

select h.hotel_name, sum(r.total_amount) as total_revenue
from hotel h
join branch b
on h.hotel_id = b.hotel_id
join room rm
on b.branch_id = rm.branch_id
join reservation r
on rm.room_id = r.room_id
group by h.hotel_name
order by total_revenue desc;

-- 7. Display the hotel name, hotel rating, and total number of branches for hotels having more than one branch. Arrange the result by the highest number of branches.

select h.hotel_name, h.hotel_rating, count(b.branch_id) as total_branches
from hotel h
join branch b
on h.hotel_id = b.hotel_id
group by h.hotel_name, h.hotel_rating
having count(b.branch_id) > 1
order by total_branches desc;

-- 8. Display the departments having more than 5 employees along with the employee count. Arrange the result in descending order of employee count.

select d.department_name, count(e.employee_id) as employee_count
from department d
join employee e
on d.department_id = e.department_id
group by d.department_name
having count(e.employee_id) > 5
order by employee_count desc;

-- 9. Display the customer name, room number, check-in date, check-out date,
--  and total number of stay days for all completed reservations. Arrange the result by check-in date.

select c.customer_name,rm.room_number,ci.checkin_date,co.checkout_date,datediff(co.checkout_date, ci.checkin_date) as total_stay_days
from checkin ci
join checkout co
on ci.reservation_id = co.reservation_id
join reservation r
on ci.reservation_id = r.reservation_id
join customer c
on r.customer_id = c.customer_id
join room rm
on r.room_id = rm.room_id
order by ci.checkin_date;

-- 10. Display the room type with the highest number of bookings.

select rt.room_type_name, count(r.reservation_id) as total_bookings
from room_type rt
join room rm
on rt.room_type_id = rm.room_type_id
join reservation r
on rm.room_id = r.room_id
group by rt.room_type_name
order by total_bookings desc
limit 1;

-- 11. Create a view to display the customer name, payment method, payment status, and payment amount. Display all records from the view ordered by payment amount.

create view customer_payment_view as
select c.customer_name, p.payment_method, p.payment_status, p.payment_amount
from payment p
join reservation r
on p.reservation_id = r.reservation_id
join customer c
on r.customer_id = c.customer_id;
select * from customer_payment_view
order by payment_amount desc;

-- 12. Create a stored procedure to display the employee name, department name, salary, and hire date for a given department ID. Arrange the result in descending order of salary.

delimiter &&
create procedure getemployeedetails(in dept_id int)
begin
select e.employee_name, d.department_name, e.salary, e.hire_date
from employee e
join department d
on e.department_id = d.department_id
where e.department_id = dept_id
order by e.salary desc;
end &&
delimiter ;
call getemployeedetails(1);

-- 13. Create a trigger to automatically update the room status to 'Booked' whenever a new reservation is inserted.

delimiter &&
create trigger update_room_status
after insert on reservation
for each row
begin
update room
set room_status = 'booked'
where room_id = new.room_id;
end &&
delimiter ;

-- 14. Display the employees whose salary is greater than the average salary of all employees. Arrange the result in descending order of salary. (Using Subquery)

select employee_name, salary
from employee
where salary >
(select avg(salary)
from employee)
order by salary desc;

-- 15. Display the employees who receive the highest salary in their respective department. Arrange the result by department name. (Using Subquery)

select e.employee_name, d.department_name, e.salary
from employee e
join department d
on e.department_id = d.department_id
where e.salary =(
select max(salary)
from employee e2
where e.department_id = e2.department_id)
order by d.department_name;
